version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    container_name: be_redis

  web:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=my.local
      - NGINX_PORT=80
    volumes:
      - $HOME/Documents/project/nginx-config:/etc/nginx/conf.d
      - $HOME/Documents/project/local:/usr/share/nginx/html
    container_name: be_nginx

  php:
    image: php:7.0-fpm-jessie
    volumes:
      - $HOME/Documents/project/local:/usr/share/nginx/html
    container_name: be_php

  db:
    image: percona
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local123
    container_name: db_percona

volumes:
  redis_data:
  nginx_data:
  percona_data: